project:
  type: website

website:
  title: "BlackMarbleR"
  favicon: images/favicon.ico
  body-header: |
    This page brought to you by <https://example.com>
  margin-header: |
    ![Packge Logo. An image of dark background with point yellow lights](images/logo.png)
  navbar:
    logo: images/logo.png
    right:
      - icon: github
        href: https://github.com/worldbank/blackmarbler/
        aria-label: GitHub
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - testing_webr.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    smooth-scroll: true

execute:
  eval: false



